# Aren't intelligence tests biased?

## Evidences of test bias

There has been much debate around the potential bias of intelligence tests. However, research has consistently shown that intelligence tests, when administered and scored correctly, are not biased against any particular group or population.

In fact, intelligence tests are designed to be culturally fair and measure cognitive abilities that are not tied to any specific cultural or socioeconomic group. The tests are created using a rigorous process that involves extensive pilot testing, item analysis, and psychometric evaluation.

Expert opinion finds that “the issue of test bias is scientifically dead” [@hunter2000 p. 151] “There exists, in contrast to the position of the late 1960s, a substantial body of research addressing the cultural test bias hypothesis, and scholars have extensively reviewed this literature in book and chapter-length forums [@jensen1980]; [@reynolds1995]; [@reynolds1998]; [@reynolds1984]. Essentially, these reviews have concluded that well-constructed, reliable, well-standardized psychological tests are not biased against native-born American racial or ethnic minorities. Studies of cultural bias in testing do occasionally reveal bias in some aspects of validity, but the bias is more likely to favor minorities in a predictive context” [@reynolds2000];[@reynolds2012] 

In 1982, the National Research Council and the National Academy of Sciences found that “ability tests predict equally well for all groups of test takers. Research evidence does not support the notion that tests systematically underpredict the performance of minority group members” [@wigdor1982] In 1994, Mainstream Science on Intelligence, a statement issued by several researchers, finds that “Intelligence tests are not culturally biased against American blacks or other native-born, English-speaking peoples in the U.S. Rather, IQ scores predict equally accurately for all such Americans, regardless of race and social class. Individuals who do not understand English well can be given either a nonverbal test or one in their native language.” [@gottfredson1997]. In 1996, the American Psychological Association found that “considered as predictors of future performance, the tests do not seem to be biased against African Americans.” [@neisser1996]. [@reeve2008] found that there is a consensus among intelligence experts that cognitive ability tests are not bias against minority groups

And most important of all: logical and empirical examination: If intelligence tests merely measure knowledge or conformity to Western middle-class culture is the fact that the racial group with the highest average on these tests is not Europeans, but East Asians; this has been true since the 1920s [@goodenough1926]. If intelligence tests measure acculturation to Western culture, then indigenous communities who have had more contact with Europeans should score higher than people in communities in the same nation who have had less contact. However, this is not the case [@porteus1965]. 

Content of many test formats (e.g., matrix tests, digit span) contains very little information that is unique to Western culture. It is not clear how numbers or geometric patterns are special to Western middle-class individuals.  Expert rated culturally loaded test items do not contribute to an increase in the Black/White divide. [@jensen1987] If test items were culturally loaded, (especially to a degree that would significantly change test results) this would mean test items ranked by difficulty would not correlate well by race. However, the opposite is true. [@reynolds2012] Correlation of rank order difficulty between cognitive batteries is nearly perfect among Blacks and Whites. 

## Evidences regarding stereotype threat

__Racial bias__

The literature on stereotype threat is not great. [@schimmack2017] We have even had papers that are completely fabricated (probably for political motivation). [@flores2020] We have a few meta analyses on this phenomenon. Publication bias plagues many of these studies and when factored for, the effect sizes decrease. [@flore2015];[@shewach2019], a meta-analysis of 212 experimental studies on stereotype threat, which included a total of more than 10,000 adult participants effects (the largest to date) 'range[d] from negligible to small' If we assume stereotype threat is an actual possible influential factor, we would actually expect Black people to have increased scores as they measure higher than whites on various psychological metrics

Compared to Whites, Blacks have higher self-esteem [@twenge2002], Lower suicide rates [@curtin2022], Lower rates of stress [@krueger2011], Lower risk for panic disorder, Lower risk for generalized anxiety order, Lower risk for social phobia [@breslau2006], Lower rates for depressive disorder [@riolo2005], Lower overall rate of mental disorders [@coleman2016]. Since Black people are more confident and mentally healthy, it doesn’t seem like stereotype threat could be a relevant factor. In conclusion: the evidence points to there being no cultural bias in IQ testing and there doesn't seem to be enough methodologically robust literature to make a certain claim on stereotype threat (though more recent analyses that factor for publication bias show null effects). The burden of proof rests on those who claim this to significantly affect the gap between blacks and whites.

