# Do scientists actually believe in general intelligence?

The theory of IQ as the measure of general intelligence is mainstream. The American Psychological Association’s authoritative task force on intelligence stated that the theory of general intelligence is "the most widely accepted current view" [@neisser1996 p. 81]. 

Fifty-eight percent of APA respondents favor some form of a general intelligence solution, whereas 13% feel separate faculties are superior. Only 16% think the data are sufficiently ambiguous as to not favor either solution. [@snyderman1987 p. 140]

Mainstream Science on Intelligence, a Wallstreet Journal editorial with 52 signatories of 25 conclusions that represent the mainstream, Gottfredson writes that "Intelligence is a very general mental capability ... it reflects a broader and deeper capability for comprehending our surroundings ..." Of the invitation sent out to 131 researchers, only 11 responded that one or more of the conclusions did not represent the mainstream. [@gottfredson1997]

In a conference attended by leading experts on human intelligence Michael Rutter, who is known for his moderate views, said: “All of us accept [g’s] reality. It is not merely a statistical artifact, rather, it really does represent something that is biologically important” [@rutter2000 p. 282]. One of the most prominent critics of general intelligence had to concede: “The evidence in favor of a general factor of intelligence is, in one sense, overwhelming ... One would have to be blind or intransigent not to give this evidence its due”
[@sternberg2003 p. 375]

Most recently, a survey of expert opinion on intelligence finds that "76% favored a general factor perspective" noting that "Experts favored a g
factor perspective" [@rinderman2020 p. 4]