# Isn't _g_ a statistical artifact?

## Are positive intercorrelations from test design?

There are many cognitive batteries that specifically do not try to look for ‘g’, some of which expressly try to avoid it. 

- Researchers for the British Ability Scales lament that “there is little evidence that strong primary factors… have accounted for any substantial proportion of the common variance of the British Ability Scales. This is despite the fact that the scales sample a wide range of psychological functions.” It asks What, then, are we to make of the results of these analyses? Do they mean that we are back to square one, as it were, and that after 60 years of research we have turned full circle and are back with the theories of Spearman?” [@elliot1986]. 

- The CAS Battery is based on the Soviet inspired [PASS theory](https://en.wikipedia.org/wiki/PASS_theory_of_intelligence) which disavows _g_ and asserts that intelligence consists of four processes called Planning, Attention-Arousal, Simultaneous, and Successive. The CAS was designed to assess these four processes. However, [@keith2001] did a joint confirmatory factor analysis of the CAS together with the WJ-III battery, concluding that not only does the CAS not measure the constructs it was designed to measure, but that notwithstanding the test makers’ aversion to g, the g factor derived from the CAS is large and statistically indistinguishable from the g factor of the WJ-III. The CAS therefore appears to be the opposite of what it was supposed to be: an excellent test of the “non-existent” g and a poor test of the supposedly real non-g abilities it was painstakingly designed to measure. 

- The triarchic theory of intelligence originated as an alternative to the concept of general intelligence factor, or g. [@vinney2021]; [@brody2003a], [@brody2003b] analyzed Sternbergs work and finds a general factor of intelligence. Additionally, with tests that are radically different, Confirmatory Factor Analysis showed that different cognitive batteries (CAB, Hawaii Battery, WAIS) were analyzed, and it turned out that the g factors computed from the three tests (five tests in [@johnson2008]) were statistically indistinguishable from one another, despite the fact that the tests tapped into partly different sets of abilities. [@johnson2004], [@johnson2008]. 

The significance of this "positive manifold" is that we would not expect someone who is good at one cognitive test to just be good at all of them. 

## Other evidence for _g_

### Predictive validity of _g_-loaded and non-_g_-loaded tasks

Practical validity: General intelligence is a good predictor of several seemingly unrelated life outcomes. For example, IQ is the best single predictor of academic and job performance and attainment, and one of the best predictors of a plethora of other outcomes, from income, welfare dependency, and criminality [@gottfredson1997b] to [health and mortality](https://en.wikipedia.org/wiki/Cognitive_epidemiology) and scientific and literary creativity [@robertson2010], and any number of other things, including even investing success [@grinblatt2012]. If you had to predict the life outcomes of a teenager based on only one fact about them, nothing would be nearly as informative as their IQ.

One interesting thing about the predictive validity of a cognitive test is that it is directly related to the test’s g loading. The higher the g loading, the better the validity. In fact, although the g factor generally accounts for less than half of all the variance in a given IQ battery, a lot of research indicates that it accounts for almost all of the predictive validity. The best evidence here are from several large-scale studies of US Air Force personnel. These studies contrasted g and a number of more specific abilities as predictors of performance in Air Force training [@ree1991] and jobs [@ree1994]. The results indicated that g is the best predictor of training and job performance across all specialties, and that specific ability tests tailored for each specialty provide little or no incremental validity over g. Thus if you wanted to predict someone’s performance in training or a job, it would be much more useful for you to get their general mental ability score rather than scores on any specific ability tests that are closely matched to the task at hand. This appears to be true in all jobs [@schmidt1998]; [@schmidt2004], although specific ability scores may provide substantial incremental validity in the case of high-IQ individuals [@robertson2010], which is in accord with Charles Spearman’s view that abilities become more differentiated at higher levels of g. (This is why it makes sense for selective colleges to use admission tests that assess different abilities.)

For more evidence of how general the predictive validity of g is, we can look at the validity of g as a predictor of performance in GCSEs ([General Certificate of Secondary Education](https://en.wikipedia.org/wiki/General_Certificate_of_Secondary_Education)), which are academic qualifications awarded in different school subjects at age 14 to 16 in the United Kingdom. [@deary2007] conducted a prospective study with a very large sample where g was measured at age 11 and GCSEs were obtained about five years later. The g scores correlated positively and substantially with the results of all 25 GCSEs, explaining (to give some examples) about 59 percent of individual differences in math, about 40 to 50 percent in English and foreign languages, and, at the low end, about 18 percent in Art and Design. In contrast, verbal ability, independently of g, explained an average of only 2.2 percent (range 0.0-7.2%) of the results in the 25 exams.

Arthur Jensen referred to g as the “active ingredient” of IQ tests, because g accounts for most if not all of the predictive validity of IQ even though most variance in IQ tests is not g variance. From the perspective of predictive validity, non-g variance seems to be generally just noise. In other words, if you statistically remove g variance from IQ test results, what is left is almost useless for the purposes of predicting behavior (except among high-IQ individuals, as noted above). This is a very surprising finding if one thinks that different mental abilities are actually independent, and g is just an uninteresting statistical artifact caused by an occasional recruitment of many uncorrelated abilities for the same task.

__Hollowness of IQ training effects__

Another interesting fact about g is that there is there is a systematic relation between g loadings and practice effects in IQ tests. A meta-analysis of re-testing effects on IQ scores showed that there is a perfect negative correlation between score gains and g loadings of tests [@tenijenhuis2007]. It appears that specific abilities are trainable but g is generally not (see also @arendasy2013). Similarly, a recent meta-analysis of the effects of working memory training on intelligence showed, in line with many earlier reviews, that cognitive training produces short-term gains in the specific abilities trained, but no “far transfer” to any other abilities [@melbylervag2013]. Jensen called such gains hollow because they do not seem to represent actual improvements in real-world intellectual performance. These findings are consistent with the view that g is a “central processing unit” that cannot be defined in terms of specific abilities and is not affected by changes in those abilities.

### Quantitative genetic evidence

On a biological level, cognitive abilities are heritable. [@polderman2015] Higher g-loadings correlate to higher heritabilities [@jensen1987],[@rushton2007], [@vanbloois2009],[@tenijenhuis2014]. Quantitative genetic analyses indicate that g is an even stronger genetic variable than it is a phenotypic variable. [@plomin2004] states, 

_"Multivariate genetic analysis yields a statistic called genetic correlation, which is an index of the extent to which genetic effects on one trait correlate with genetic effects on another trait independent of the heritability of the two traits. That is, two traits could be highly heritable but the genetic correlation between them could be zero. Conversely, two traits could be only modestly heritable but the genetic correlation between them could be 1.0, indicating that even though genetic effects are not strong (because heritability is modest) the same genetic effects are involved in both traits. In the case of specific cognitive abilities that are moderately heritable, multivariate genetic analyses have consistently found that genetic correlations are very high—close to 1.0 [@petrill1997]. That is, although Spearman’s g is a phenotypic construct, g is even stronger genetically. These multivariate genetic results predict that when genes are found that are associated with one cognitive ability, such as spatial ability, they will also be associated just as strongly with other cognitive abilities, such as verbal ability or memory. Conversely, attempts to find genes for specific cognitive abilities independent of general cognitive ability are unlikely to succeed because what is in common among cognitive abilities is largely genetic and what is independent is largely environmental."_


### Neurobiological correlates

The controversy if brain anatomy correlates with intelligence has existed for decades but since the 1980s some neuroscientists have worked to bridge the gap between these two fields, and in the twenty-first century their evidence and theories support the belief that g does indeed have connections to brain anatomy and functioning twenty-first century their evidence and theories support the belief that g does indeed have connections to brain anatomy and functioning [@haier2017].

__Brain Volume__

There are brain characteristics that do correlate with IQ scores. One of the best known is the correlation between brain size and intelligence, which when measured via brain-imaging techniques in living individuals is between r = .20 and .40. Other measures of brain size (e.g., data from autopsies, or measures of head circumference) have weaker, though positive, correlations [@cox2019]; [@gignac2017]; [@lee2019]; [@pietschnig2015]; [@rushton2009]. A 2022 meta-analysis ultimately states that most reasonable estimates for the brain size and IQ link yield r-values in the mid-0.20s, with the most extreme specifications yielding rs of 0.10 and 0.37. [@pietschnig2022]. Additionally, measures of the size of the whole brain are more strongly correlated than measures of specific brain regions. It is important, though, to note that the size of the frontal lobes seems more strongly correlated with IQ than other regions of the brain [@cox2019]; [@flashman1997]. 

There seems to be some sort of association with _g_ since better measures of g produce stronger correlations with brain size [@gignac2017], [@pietschnig2022]. The relationship between brain volume and IQ is clearly complex and seems to be modestly moderated by g. [@woodleyofmenie2016]


__Other Brain Characteristics__

Since the 1990s, neuroscientists have discovered more variables correlated with IQ. For example, research has shown the importance of the white matter in the brain, which is the tissue that connects brain regions to one another. Volume of white matter is correlated with speed of problem solving [@penke2012] and with IQ, thus showing that connectivity of brain regions is likely to be an important determinant of intelligence levels [@haier2017]; [@kievit2016]. Likewise, grey matter (where the neuron cell bodies are found) is important; loss of neurons due to disease is associated with decreases in IQ [@vanveluw2012]. Additionally, smarter people have more neurons in their brains, and those neurons are more densely packed together [@genç2018]. Another intriguing recent finding is that neurons are better organized in high-IQ  ndividuals’ brains than in the brains of people who score poorly on intelligence tests.

