# Isn't IQ only useful for cognitively disabled people?

The “threshold hypothesis” states that increased IQ does not lead to additional benefits- though the actual line of the threshold is disputed. [@gladwell2008] states that the threshold is at an IQ of 120 (which would mean mathematically that over 90 percent of the population experience noticeable benefits with higher IQ). A different estimate by [@feldman1984] says that the threshold is about IQ 150 (which excludes less than 1 percent of the population). 

Based on the best available research, the threshold hypothesis is incorrect. Data from large samples of high-IQ people show that the likelihood of beneficial life outcomes continues to increase as people get smarter. The best research on the threshold hypothesis comes from SMPY. In the SMPY sample, there are over 2,300 people who have IQs of 135 or higher – the top 1% of the population. Even within this bright group, IQ was positively correlated with favorable work and educational outcomes. For sample members in the top quarter of the top 1%, the odds of earning a doctorate were 3.56 times higher than for people whose IQ was “only” in the bottom quarter of the top 1%. In the SMPY sample, the odds of a person in the brighter group were also higher for having an income in the top 5% of incomes nationwide (2.31 times greater); earning a patent (3.01 times greater); publishing a literary work (4.55 times greater); and publishing scholarly work in science, technology, engineering, or mathematics (4.97 times greater). There was no apparent threshold where the probability of any accomplishments leveled off or decreased [@lubinski2009]. Selecting an even higher threshold of an IQ of 156 (the top 0.01% of the population, or the top 1 in 10,000 people) does not diminish the threshold effect. Over 50% of SMPY sample members with IQs of 156 or higher earned doctorates, while “only” 30% of the top 0.5% (IQ of 139 or higher) earned a doctorate [@lubinski2009] (In comparison, 1.8% of the US adult population has earned a doctorate).

Moreover, people with IQ scores in the top 1 in 10,000 rise to the top echelons of leadership and productivity in their careers at such a high rate that, “many are outstanding creators of modern culture, constituting a precious human-capital resource” [@kell2013 p.648]. The results of SMPY have been replicated. [@wai2014 p.76] found that within a sample of 1,536 teenagers with IQ scores in the top 1% (IQ of 135 or higher), the smartest 25% earned doctorates at a rate that  was 1.52 times. greater than the least intelligent 25%. Another sample of individuals with IQs in the top 1 in 10,000 of the population had similar levels of high education achievement, work productivity, and eminence within their fields as was found in the SMPY sample [@makel2016]. [@coyle2015] reported data from two studies on the relationship between intelligence and college grade point averages and found that the correlation was constant across the entire range of intelligence levels. In other words, there was no point at which greater levels of intelligence failed to increase the probability of a high grade point average in college. In a sample of gifted children, [@ruf2005] found that as IQ increased, children were better able to move through the K-12 curriculum quickly and were increasingly more likely to display early academic development, such as learning to read by age. Successively brighter groups also mastered advanced academic material at younger and younger ages. Another study that disproves the threshold hypothesis showed that in a large sample of medical school graduates higher scores on achievement tests needed to obtain a medical license were always associated with higher levels of competence in practice [@wakeford2018].
