# Aren't other models of intelligence more valid?

## Don't we have multiple intelligences?

The theory of multiple intelligences proposes the differentiation of human intelligence into specific intelligences, rather than defining intelligence as a single, general ability. [@gardner2011]

Gardner, the creator of the theory of multiple intelligences states that “I readily admit that the theory [of multiple intelligences] is no longer current. Several fields of knowledge have advanced significantly since the early 1980s. Any reinvigoration of the theory would require a survey similar to the one that colleagues and I carried out thirty-five years ago.” [@sternberg2016 p. 169–170]. @hunt2010 p. 119,  stated that “there is virtually no objective evidence for the theory” of multiple intelligences. Gardner believes that those who espose general intelligence are “bad guys”. [@gardner2009] Gardner seems to have called the abilities in his model, “intelligences” in order to “replace the current, [allegedly] largely discredited notion of intelligence as a single inherited trait” [@gardner2011 p. 300]. 

By including physical abilities (in bodily-kinesthetic intelligence), personality traits (in interpersonal intelligence) and other non-cognitive traits, Gardner has stretched the word “intelligence” so much that it ceases to have any real meaning [@hunt2010];[@jensen1998];[@scarr1985]. Gardner sees g as being a narrow concept that encourages “a limited view of intelligence” [@vonkaroli2002], but believing in the existence of g does not preclude the existence of other abilities. In fact, both the currently accepted model of intelligence, the Cattell-Horn-Carroll model and bifactor models explicitly recognize the existence of non-g cognitive abilities 

In order to make the theory of Multiple Intelligences, Gardner habitually cherry picks evidence in his favor and ignores evidence that contradicts his theory [@bouchard1984]; [@messick1992]; [@scarr1985]; [@snow1985]. Frames of Mind also has the drawback of relying heavily on anecdotal data rather than any large, representative sample of individuals performing tasks grounded in his intelligences [@lubinski1995]. 

Gardner’s theory is also unfalsifiable. Gardener states that he has “never felt that MI theory was one that could be subjected to an ‘up and down’ kind of test, or even series of tests” [@gardner2011, p. xix]. And that he “[does] not believe that educational programs created under the aegis of MI theory lend themselves to the kinds of randomized control studies that the US government is now calling for in education” [@gardner2011, p. xxi]. Gardner has stated that he does not endorse any psychological test to measure the multiple intelligences [@vonkaroli2002].

## Isn't Emotional Intelligence or EQ more powerful than IQ?

Emotional Intelligence, “the capacity to reason, understand, and manage emotions. In addition, emotional intelligence plausibly reflects the emotion system’s capacity to use emotion to enhance thought”. Goleman describes it as “the ability to identify, monitor and accurately use information about emotional states” After Goleman’s 1996 book, “Emotional Intelligence”, the popular psychological term became a multi-million dollar industry. [@grewal2005] This fad [@murphy2006], like other fads in psychology, is unsubstantiated by the literature. Emotional Intelligence is not actually an independent construct, it seems to just measure various other factors that predict success. [@joseph2015] reports that “62% of the variance in mixed EI is captured by Conscientiousness, Extraversion, Emotional Stability, ability EI, cognitive ability, general self-efficacy, and self-rated job performance.” which are all factors that predict success. This is also explored in [@landy2005]. 

Emotional Intelligence's construct validity is in question as some show it may merely be a repackaged version of the Big Five personality traits [@conte2005]; [@canderlinden2018]. 

@davies1998 states _"Our searches of the literature revealed only six articles in which the authors either explicitly examined the incremental validity of EI scores over measures of both cognitive ability and Big Five personality traits in predicting either academic or work performance, or presented data in a manner that allowed examination of this issue. Not one of these six articles... showed a significant contribution for EI in the prediction of performance after controlling for both cognitive ability and the Big Five..._

_For correlations involving the overall EI construct, EI explained almost no incremental variance in performance [change in prediction] = .00. Findings were identical when considering only cases involving an ability-based measure of IE...."._ 

@harms2010 states _"...proofs of validity [for EI] seem to come from measuring constructs that have existed for a long time and are simply being relabeled and recategorized. For example, one of the proposed measures of (Emotional and Social Competence), the Trait Emotional Intelligence Questionnaire, makes use of measures of assertiveness, social competence, self-confidence, stress management, and impulsivity among other things. Most, if not all, of these constructs, are firmly embedded in and well-accounted for by [other] well-designed measures of personality traits..._ 

The substantial relationships observed between these ESC (Emotional and Social Competence) and trait-based EI measures, and personality inventories bear this out. It, therefore, appears that the predictive validity of ESC or EI measures may be accounted for in large part by the degree to which they assess sub-facets of higher-order traits relevant to the outcomes being predicted.

## Is IQ the only trait that predicts outcomes?

Although intelligence is important in determining a student’s level of academic success, no one claims that intelligence is the only trait that impacts school outcomes. The correlation between IQ and measures of academic success – such as grades, standardized test scores, or how many years a person stays in school – is not perfect. That means that there is room for other abilities to exert an impact on educational performance. As @gottfredson1997b p.116 states, _“The effects of intelligence ... are probabilistic, not deterministic. Higher intelligence improves the odds of success in school and work. It is an advantage, not a guarantee. Many other things matter.”_ It is not difficult to brainstorm a list of what these “other things” that influence success are. Psychological traits like motivation, creativity, resiliency, curiosity, industriousness, and ambition can all be important for doing well in school. Non-psychological variables like socioeconomic status, parental involvement in education, a culture that encourages academic competition, and good physical health could also have an impact on a student’s success [@warne2016]. Nobody denies this- but whether or not these variables  

The argument among psychologists and educators is not whether non-cognitive variables can result in higher school performance. Rather, the argument is over the magnitude of the influence that these non-cognitive variables have and whether these variables are more important than intelligence in determining educational success. Personality traits have moderate importance in determining school performance, but they are hard to change. This resistance to interventions is probably because personality traits are – like almost every other psychological trait – partially influenced by genes. The heritability of personality is roughly the same as the heritability of intelligence, which may limit the malleability of personality [@bouchard1997]; [@bouchard2004]; [@briley2017]. Because of the difficulty of improving school performance by altering personality, many psychologists seek non-cognitive characteristics that are both malleable and important causes of academic achievement.

### Personality traits 

The leading theory for personality, the Five Factor model, these traits are present in many cultures and across the lifespan, and they are a robust basis for understanding personality [@allik2017]. Psychologists have conducted a great deal of research on the correlation between Big Five traits and school success. Although not perfectly consistent, this research shows that some of these traits correlate with educational outcomes. Conscientiousness has the strongest correlation, usually between r ≈ .20 and .35 (e.g., [@cucina2016]; [@lechner2017]; [@poropat2009]; [@spinath2010]). While this is a strong enough correlation for conscientiousness to be a noteworthy influence on school performance, it is weaker than the correlation between intelligence and academic performance, which is usually r ≈ .35 to .70 in the same studies. This indicates that intelligence is a more important influence on educational performance than conscientiousness is. The other personality traits in the Big Five have weaker relationships – in some studies as weak as zero – with academic achievement.

### Motivation 

There is no denying the benefits of motivation. As one of the best non-cognitive influences on academics [@rosen2010]; [@liu2012], it is no surprise we see that motivated people set higher goals and accomplish more goals [@locke2002]. Policies that encourage motivation in children result in greater dedication to their studies and higher performance in school (e.g., [@patall2008]; [@roderick2001]). 

Motivation, school performance, and IQ are all positively correlated with one another, and it is often difficult to disentangle their influences. In regards to intelligence, research shows that highly motivated examinees earn slightly higher IQ scores [@gignac2019]. And because staying in school longer raises IQ [@ceci1991]; [@ritchie2018], it is possible that academically motivated students – who choose to stay in school longer – might earn higher IQs because of their additional education. However, none of this is evidence for whether increased motivation can cause higher g. Controlling for intelligence sometimes makes the relationship between motivation and academic performance disappear (e.g., [@ziegler2010]), though not always. And it is possible that motivation’s impact on IQ is entirely on the non-g influences on test scores.  It does seem clear that improving student motivation can lead to gains in educational performance [@rosen2010]. Motivation seems to have a stronger effect on grades than on standardized test scores (e.g., [@cucina2016]), possibly because earning high grades requires more sustained effort.  Regardless, intelligence seems to be the more important predictor, no matter how academic performance is measured. As the authors of one study stated, “cognitive abilities were by far the best predictor of school achievement” [@gagné2001 p.71]. Motivation – important as it is in determining academic outcomes – still is dwarfed by the influence of intelligence and other cognitive abilities. Therefore, no amount of motivation can make up for a large IQ deficit.

### Mindset

According to Dweck, there are two types of mindset: (a) fixed mindset and (b) growth mindset. [@dweck2009]. There are several things that growth mindset are set out to achieve, most of which are minor or even associated with negative effects. Growth mindset is only slightly associated with goal setting. [@burgoyne2020] finds a correlation of 0.1 between having a growth mind-set and holding learning goals. For comparison, other personality constructs have been found to correlate much more strongly with learning goal orientation: self-efficacy (r = .56), need for achievement (r = .38), and openness to experience (r = .34); [@payne2007]. Conversely, [@burgoyne2020] finds no statistically significant associations between having a fixed-mindset and and performance goals. People with growth mindsets are not more intelligent. If anything, it is the opposite. [@macnamara2017] find a insignificant correlation between mind-set and intelligence RMP (β = -0.04) [@burgoyne2020] interestingly finds that mind-set has a very small negative correlation with cognitive ability tests. CFIT-4 (β = -0.10), Letter sets (β = -0.11), RPM (β = -0.12) People with growth mindset do not achieve more. [@bahník2017] using university applicants who took an exam on scholastic aptitude (N = 5653) finds that growth mind-set was not positively associated with results of the test, did not predict change of the results for those who retook the test, did not predict participation in a future administration of the test, nor could it predict the total number of tests taken. [@sisk2018], finds only a small correlation between mind-set and academic achievement (r = 0.1 and r=.08). [@li2020] find no association between growth mind-set and academic achievement. Growth mindset does not improve resilience- if anything, it is negatively associated with resilience. Li and Bates 2019; [@burgoyne2020]

### Grit

Grit, formulated by Angela Duckworth, is perseverance and passion for long-term goals. [@duckworth2007 p.1087–1088] Grit seems to be extremely similar to the Big 5 trait, “conscientiousness”. The two traits correlate at = .66 to .84 [@crede2016]. This correlation is so high that it indicates that there is little, if anything, new about grit at all. It is probably just a repackaged version of conscientiousness. A growing body of research studies shows that grit has no unique properties compared to more established non-cognitive variables (e.g., [@dixson2016]; [@usher2019]). Grit also does not seem like it can be grown. @rimfeld2016 finds that grit was substantially heritable, but found no evidence for a shared environmental influence on grit. @rimfeld2016 p. 786 explained that _"[t]he most limiting finding, for any possible intervention, is that shared environmental influence is negligible"_. Regardless, intelligence contributes 48-90 times more than grit and has a negligible effect on educational and economic success [@zisman2021]. @crede2016 p.501 conducted a meta-analysis investigating the influence of grit and other traits on academic achievement, and found that while conscientiousness explained variance in academic achievement after controlling for grit, _"overall grit explains no variance in either overall academic performance or high school GPA after controlling for conscientiousness"_

## What about mutualism?
Mutualism, which states that "cognitive processes are initially uncorrelated, but that the positive manifold arises during individual development due to mutual beneficial relations between cognitive processes.", has no good empirical backing. Mutualism expects that “it takes some time for the positive manifold, and thus the psychometric g factor, to emerge”, [@vandermaas2006 p.851] but conversely, the proportion of variance in scale scores accounted for by a general factor is stable from age 2.5-90 [@gignac2014]; @thompson1985 even finds evidence for a genetic ‘g’ among infants. Mutualism would expect low genetic correlations among cognitive domains, however, more g-loaded tests are more heritable than the less g-loaded tests (and this exists in non humans as well). This is incredibly problematic. For example, in children, “correlations between phenotypic g loadings and genetic g loadings were 0.88 and 0.76 for the two mental test batteries.” [@deary2006] Additionally, “the effect of being raised in the same family is smaller than the effect of genes.” (Second Law of Behavioral Genetics) Mutualism fails to pass lex parsimoniae, is not generalisable, is not falsifiable, and is based mostly on post-hoc justifications [@gignac2016]. Finally, under mutualism, we would expect changes to ‘g’ occurring after social changes and environmental impacts. However, IQ gains from adoption are not g-loaded, [@tenijenhuis2015] IQ changes with education are not g-loaded [@tenijenhuis2014b]; [@ritchie2015], etc.
