# Aren't people with higher IQs more likely to be mentally ill?

For social and emotional outcomes, there is not much evidence about whether an IQ threshold exists. In the best study on this topic [@guldemond2007], children above IQs of 130 and 144 did not have more social or emotional problems than children with IQs in the 110s and 120s. Ironically, the evidence indicates that high intelligence may be a protective factor against at least some forms of psychiatric illness [@savage2018]; [@walker2002]. This is especially apparent in GWAS results, which show that some of the DNA segments associated with higher IQ are often negatively correlated with mental health problems [@hill2019]; [@savage2018]; [@sniekers2017], which makes it especially unlikely that people with very high IQs experience more psychiatric illnesses. An important exception to this general trend is autism spectrum disorder, which seems to share some genes in common with high intelligence [@hill2019]; [@savage2018]; [@sniekers2017]. [@williams2022] finds that high intelligence is not a risk factor for mental health disorders

