project:
  type: book
  output-dir: docs

book:
  title: "IQ"
  favicon: bulb.png
  author: "Aj!"
  date: "4/12/2023"
  chapters:
    - index.qmd
    - justtests.qmd
    - trustworthy.qmd
    - notuseful.qmd
    - sesfactors.qmd
    - statartifact.qmd
    - altmodels.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly

  pdf:
    documentclass: scrreprt



