project:
  type: book
  output-dir: docs


website:
  favicon: images/bulb.png

book:
  title: "IQ"
  author: "Aj!"
  date: "4/5/2023"
  chapters:
    - index.qmd
    - 2justtests.qmd
    - 3trustworthy.qmd
    - 4notuseful.qmd
    - 5sesfactors.qmd
    - 6statartifact.qmd
    - 7altmodels.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: pulse
  pdf:
    documentclass: scrreprt



