project:
  type: book
  output-dir: docs


book:
  title: "IQ"
  author: "Aj!"
  date: "4/5/2023"
  chapters:
    - index.qmd
    - 1tooabstract.qmd
    - 2justtests.qmd
    - 3testbias.qmd
    - 4unreliablepsych.qmd
    - 5consensus.qmd
    - 6thresholdhyp.qmd
    - 7mentallyill.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: pulse
  pdf:
    documentclass: scrreprt



