# Aren't people are low IQ because they’re poor?

Firstly, we have to understand that IQ is designed to be a measurement of intelligence. Like all models, it is subject to noise. The interplay between intelligence and socioeconomic status is complicated and should be treated as such. Firstly, we know that intelligence and socioeconomic status correlate but this, however, does not necessarily imply causation in any specific direction. 

[@sirin2005] meta-analyzed data on roughly 100,000 students and found the mean correlation between cognitive ability and parental SES to be .28, indicating a moderate relationship. [@neisser1996] from the American Psychological Association task force report on intelligence explains that these two variables influence each other. A meta-analytic review of the longitudinal research on IQ and SES, found that the mean correlations between a person’s IQ measured at one point and their education, occupation status, and income, measured 10 or more years later, were .49, .41, and .22 respectively. This is significant because they were better predictors than their parental socioeconomic status. [@stenze2007]; [@murray1998] analyzed data from the NLSY and showed that IQ differences within sibling pairs predicted future differences in SES. That is, the sibling with a higher IQ typically ended up having more education, a higher status occupation, and more income. 

Because siblings have identical parental SES, this analysis shows that IQ leads to higher SES independent of parental SES. This is also recorded in [@lubinski2009b]. 

Twin studies can additionally give insight on the variation of intelligence attributed to the common or shared environment. Common environmental influence, which includes familial socioeconomic status, influences 25 percent the variability and decreases to around 15 percent of the variability in young adulthood- the maximum amount of influence that socioeconomic factors from family could play. [@haworth2010]

Acting as a natural experiment, some evidence shows that adoption may raise IQ since adoption into a highly favorable environment would be described as an “intensive, years-long intervention that includes academic, social, and health improvements throughout childhood and adolescence” [@warne2020] However, this kind of adoption as stated above seems to increase IQ scores of around 4 points. [@kendler2015] (though this may not be in g itself [@tenijenhuis2015]). More generally, [@mcgue2007] studies adoptive and non adoptive families, each consisting of an adolescent sibling pair and one or both of their parents (with comparable age and gender). This study does not find that socioeconomic status is a causal element in determining intelligence. 
